### ISSUE TITLE
Other Challenges

### ISSUE THREAD

**Issue by RimuruKece** [QuePast/hcaptcha-enterprise-solver#1]
Can you make a solver for challenges like this?
![Screenshot_20241107-181255](https://github.com/user-attachments/assets/5dc9c620-f65b-4288-b853-4a945e617d8e)

**Comment by QuePast** [comment]
Hello, my solution was for last week challenge and I was using only weak cpu(not gpu cuda cores). They change some of them every week. This week challenges are also solvable you just need to think differently about them. Some of them need sobel-feldman edge detection and lot of manual work.

It was my first machine learning project. It was lot of fun. But manually gathering images from captcha every week gets kinda boring 😁

**Comment by RimuruKece** [comment]
Thanks a lot for the tips! Will try using the Sobel-Feldman method and continue exploring other ways as well.
